services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  # Node api service
  api:
    build: .  # This tells Docker Compose to build the image using the Dockerfile in the current directory
    ports:
      - 3030:3030
    depends_on:
      - mongo_db
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/dealershipsDB  # Pass MongoDB URI as an environment variable

volumes:
  mongo_data: {}
